services:
  lucos_contacts_googlesync_import:
    build: .
    container_name: lucos_contacts_googlesync_import
    environment:
      - USER_EMAIL
      - GROUP
      - DEAD_GROUP
      - PRIVATE_KEY
      - CLIENT_EMAIL
      - LUCOS_CONTACTS
      - KEY_LUCOS_CONTACTS
      - SCHEDULE_TRACKER_ENDPOINT
    image: lucas42/lucos_contacts_googlesync_import
    restart: always