version: '3'
services:
    lucos_contacts_googlesync_import:
      build: .
      container_name: lucos_contacts_googlesync_import
      environment:
        - USER_EMAIL
        - GROUP
        - PRIVATE_KEY
        - CLIENT_EMAIL
        - LUCOS_CONTACTS=https://contacts.l42.eu/
      image: lucas42/lucos_contacts_googlesync_import
      entrypoint: pipenv run python -u import.py